server:
  port: 8769
spring:
  application:
    name: tesla-zuul-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: order-service
    api-b:
      path: /api-b/**
      serviceId: inventory-service