eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: gateway-server
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: tesla-books-service
    api-b:
      path: /api-b/**
      serviceId: tesla-order-service